services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blogiadb
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro
    ports:
      - "5432:5432"

  backend:
    build: ../backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: username
      DB_PASSWORD: password
      DB_NAME: blogiadb
      HF_API_KEY: "Your key"
      PORT: 4000
    depends_on:
      - db
    ports:
      - "4000:4000"

  frontend:
    build: ../frontend
    depends_on:
      - backend
    environment:
      ASSET_DIR: /usr/share/nginx/html
      APP_PREFIX: PREFIX_
      PREFIX_API_URL: "http://localhost:4000"
    ports:
      - "3000:80"

volumes:
  db-data:
